# This file must be locate in the Home directory

set -g default-terminal "screen-256color"

# Basic prefix
set -g prefix C-a
unbind C-b

# Change the default delay
set -sg escape-time 1

# Sort by name
bind s choose-tree -sZ -O name

# Change the indexes
set -g base-index 1
setw -g pane-base-index 1

# Rebinding keys
bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind C-a send-prefix

# Splitting panes
bind | split-window -h
bind - split-window -v

# Movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5 

# Handling the mouse
setw -g mouse on

# List of plugins (Press prefix + I to fetch the plugin and source it)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'

set -g @themepack 'powerline/default/orange'

set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

# Initialize TMUX plugin manager (keep this line at the very bottom of the tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
